# Generated by Django 5.0.6 on 2024-08-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Discounted_price',
        ),
    ]
