# Generated by Django 5.0.6 on 2024-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dis',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
