# Generated by Django 5.0.6 on 2024-09-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_dis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dis',
            new_name='detail',
        ),
    ]
