# Generated by Django 5.0.6 on 2024-10-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_color_customization_fabric_gsm_material_size_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(max_length=20)),
                ('Size', models.CharField(max_length=20)),
                ('Customization', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Color', models.CharField(max_length=20)),
                ('Fabric', models.CharField(max_length=20)),
                ('GSM', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customizations',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabrics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gsms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='types',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='Fabric',
        ),
        migrations.DeleteModel(
            name='GSM',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
