# Generated by Django 5.0.6 on 2024-10-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='store.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='customizations',
            field=models.ManyToManyField(blank=True, to='store.customization'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabrics',
            field=models.ManyToManyField(blank=True, to='store.fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='gsms',
            field=models.ManyToManyField(blank=True, to='store.gsm'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, to='store.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='store.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(blank=True, to='store.type'),
        ),
    ]
