# Generated by Django 5.0.6 on 2024-10-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_product_material_product_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='Color',
            new_name='color',
        ),
    ]
