# Generated by Django 5.0.6 on 2024-10-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_rename_type_type_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='Customization',
            new_name='customization',
        ),
        migrations.RenameField(
            model_name='fabric',
            old_name='Fabric',
            new_name='fabric',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Material',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='Size',
            new_name='size',
        ),
    ]
