# Generated by Django 5.0.6 on 2024-12-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_quantity1_alter_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity1',
            new_name='Chosequantity',
        ),
        migrations.RenameField(
            model_name='chosequantity',
            old_name='color',
            new_name='Chosequantity',
        ),
    ]
