# Generated by Django 5.0.6 on 2024-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_rename_quantity1_chosequantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chosequantitys',
            field=models.ManyToManyField(blank=True, to='store.chosequantity'),
        ),
    ]
