# Generated by Django 5.0.6 on 2024-12-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_product_chosequantitys'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chosequantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
