# Generated by Django 5.0.6 on 2024-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_order_chosequantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='customization',
            field=models.CharField(max_length=50),
        ),
    ]
