# Generated by Django 5.0.6 on 2024-12-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_customization_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fabric',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='customization',
            field=models.CharField(max_length=20),
        ),
    ]
