# Generated by Django 5.0.6 on 2024-12-24 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_order_fabric_alter_customization_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
