# Generated by Django 5.0.6 on 2024-12-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
