# Generated by Django 5.0.6 on 2024-12-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_product_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
