# Generated by Django 5.0.6 on 2024-12-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_product_image10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image9',
        ),
    ]
