# Generated by Django 5.0.6 on 2024-12-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_product_image4_product_image5_product_image6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image9',
        ),
    ]
