# Generated by Django 5.0.6 on 2024-12-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_remove_product_image5_remove_product_image6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
