# Generated by Django 5.0.6 on 2025-02-14 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_remove_order_image_product_image10_product_image11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
