# Generated by Django 5.0.6 on 2025-02-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_customer_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
    ]
