# Generated by Django 5.0.6 on 2025-02-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_remove_customer_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='security_answer_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_answer_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_answer_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_question_1',
            field=models.CharField(default='Default Question', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_question_2',
            field=models.CharField(default='Default Question', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_question_3',
            field=models.CharField(default='Default Question', max_length=200),
        ),
    ]
