# Generated by Django 5.0.6 on 2025-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_remove_customer_security_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_pet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
