# Generated by Django 5.1.6 on 2025-02-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_customer_city_of_birth_customer_favorite_pet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='favorite_pet',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_school',
        ),
        migrations.AddField(
            model_name='customer',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_question_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
