# Generated by Django 5.1.6 on 2025-02-19 16:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_remove_customer_city_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
