# Generated by Django 5.1.6 on 2025-02-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
