# Generated by Django 5.1.6 on 2025-02-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_order_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='attachments',
        ),
    ]
