# Generated by Django 5.1.6 on 2025-02-20 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_order_cart_number_alter_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Designing & Quotation', 'Designing & Quotation'), ('Pending Customer Approval', 'Pending Customer Approval'), ('Order Under Production', 'Order Under Production'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Designing & Quotation', max_length=50),
        ),
    ]
